### ISSUE TITLE
Most recent iteration gives poor feedback

### ISSUE THREAD

**Issue by practicingmusician** [practicing-musician/PracticingMusicianListener#3]
You'll see what I mean.  The automated testing feature is very necessary right about now.

**Comment by jnpdx** [comment]
Version that works: 
https://github.com/practicing-musician/PracticingMusicianListener/commit/6d68407f8deaece0c8cc96c16cccf647717141e0

Broken as of: https://github.com/practicing-musician/PracticingMusicianListener/commit/878dac5ac53ce6e2fce9cf36bd90e6e70c7e6b03

**Comment by practicingmusician** [comment]
Pitch detection works well when I play the correct notes.  When I play incorrect notes, it's not displaying the correct... correction...  So I played Oh When The Saints in G Major over the Bb Major score.  The video is in your email.

**Comment by jnpdx** [comment]
As we've talked about before, it's not really realistic to play every single note incorrectly and expect it to give perfect feedback.  The new version will be slightly better at this, but even then, it'll have trouble, since it has difficulty guessing what notes are supposed to be what (especially with the rhythm and pitch tolerances as high as we have them).

I just went through and tried playing an occasional wrong note (rather than every one wrong) and it did pretty well.

My suggestion is that we leave it as-is for now and then you can re-evaluate this once the new analysis is up and running

**Comment by practicingmusician** [comment]
Ok, leave it as-is for now.
